<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="0" name="Failed suite [Surefire suite]">
  <test thread-count="1" verbose="0" name="Surefire test(failed)">
    <classes>
      <class name="rahulshettyacademy.tests.ErrorValidationsTest">
        <methods>
          <include name="LoginErrorValidation"/>
          <include name="tearDown"/>
          <include name="ProductErrorValidation"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- rahulshettyacademy.tests.ErrorValidationsTest -->
      <class name="rahulshettyacademy.tests.SubmitOrderTest">
        <methods>
          <include name="OrderHistoryTest"/>
          <include name="tearDown"/>
          <include name="submitOrder"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- rahulshettyacademy.tests.SubmitOrderTest -->
      <class name="cucumber.TestNGTestRunner">
        <methods>
          <include name="runScenario" invocation-numbers="0"/>
          <include name="tearDownClass"/>
          <include name="setUpClass"/>
        </methods>
      </class> <!-- cucumber.TestNGTestRunner -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
